[package]
name = "ado"
version.workspace = true
edition.workspace = true

[dependencies]
adolib.workspace = true
clap.workspace = true
derive_more.workspace = true
directories.workspace = true
figlet-rs.workspace = true
log.workspace = true
ratatui.workspace = true
rust-embed.workspace = true
serde_json.workspace = true
syntect.workspace = true
tempfile.workspace = true
tokio.workspace = true
tui-textarea.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
home.workspace = true

[lints]
workspace = true
