[package]
name = "ado"
version.workspace = true
edition.workspace = true

[dependencies]
adolib.workspace = true
clap.workspace = true
colored.workspace = true
derive_more.workspace = true
directories.workspace = true
figlet-rs.workspace = true
log.workspace = true
rust-embed.workspace = true
rustyline.workspace = true
serde_json.workspace = true
spinner.workspace = true
tempfile.workspace = true
tokio.workspace = true
which.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
home.workspace = true
