[package]
name = "ado"
version = "0.1.3"
edition = "2024"

[dependencies]
clap.workspace = true
log.workspace = true
adolib.workspace = true
tokio.workspace = true
rustyline.workspace = true
colored.workspace = true
which.workspace = true
spinner.workspace = true
derive_more.workspace = true
serde_json.workspace = true
directories.workspace = true
figlet-rs.workspace = true
rust-embed.workspace = true
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
home.workspace = true
